### ISSUE TITLE
Brødtekst på forsiden

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#12]
Det hadde vært antakelig vært fint med litt brødtekst før "kortene" med de forskjellige gruppene på forsiden.

**Comment by nilsfearnley** [comment]
Intro + lenke til tøi-rapporten som dette bygger på.

**Comment by nilsfearnley** [comment]
Kollektivkalkulatoren er et nyttekostnadsberegningsverktøy for enklere kollektivtransporttiltak. Kalkulatoren følger gjeldende tilnærming og metodikk for nyttekostnadsanalyser i transportsektoren. Derfor kan NKA-beregningene sammenlignes med andre samferdselstiltak. 

Velg hovedkategori av tiltak fra boksene nedenfor, og deretter konkret tiltak. Ved å legge inn bakgrunnsinformasjon om prosjektet, beregner kalkulatoren nytte for ulike aktører, tiltakets nettonåverdi og nettonytte per budsjettkrone (nyttekostnadsbrøk).

Kalkulatoren viser ved hjelp av en graf hvordan tiltakets nettonåverdi varierer med nivået på en valgt forutsetning. På den måten kan kalkulatoren brukes selv om ikke alle forutsetninger er kjent.

Beregningsopplegget er dokumentert i [TØI-rapport 1121](https://www.toi.no/publikasjoner/article29858-8.html). Her fins også nærmere veiledning til utfylling og bruk av kalkulatoren.

**Comment by 7er** [comment]
Ny versjon med brødteksten lagt ut
