### ISSUE TITLE
Endring av Tiltakstitler

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#14]
Disse bør gås igjennom og rettes der hvor de er feil

**Comment by nilsfearnley** [comment]
Navn på tiltakene
Tekst i innfyllingsboksene
Titler på innfyllingsboksene

**Comment by 7er** [comment]
Endre navn på tiltak:
 «Pakke: Leskur og sitteplass på holdeplass». Endre til: «Leskur med sitteplass»
 «Pakke: Elektronisk skilting + Opprop i bussen av neste holdeplass». Endre til «Elektronisk
skilting og opprop i bussen av neste holdeplass»
 Endre «Kollektiv prioritering lyskryss» til «Kollektivprioritering i lyskryss»

Navn og forklaring på innfyllingsbokser:
Alle tiltakene under Informasjon, unntatt Informasjon over høyttaler på holdeplass om avvik:
 Forklaringstekst inni innfyllingsboksen for antall passasjerer per år bør endres til: «Årlig
antall passasjerer om bord» (istedenfor «påstigende passasjerer per år»)

Tiltak «Informasjon over høyttaler på holdeplass om avvik»:
 Forklaringstekst inni innfyllingsboksen for antall passasjerer per år bør endres til: «Årlig
antall påstigende passasjerer på holdeplassen» (istedenfor «påstigende passasjerer per år»)
Tiltakene Sitteplass på holdeplass, Leskur uten sitteplass, Pakke: Leskur og sitteplass på
holdeplass:
 Forklaringstekst inni innfyllingsboksen for antall passasjerer per år bør endres til: «Årlig
antall påstigende passasjerer på holdeplassen» (istedenfor «påstigende passasjerer per år»)
 Forklaringstekst inni innfyllingsboksen for antall passasjerer per år bør endres til: «Årlig
antall påstigende passasjerer på holdeplassen» (istedenfor «påstigende passasjerer per år»)
Kollektivprioritering lyskryss
 Antall passasjerer ombord per år: Forklaringstekst inni boksen skal være: «Antall
kollektivpassasjerer som omfattes av tiltaket»
 Antall forsinkete biler per avgang: Forklaringstekst inni boksen kan være: «Antall biler som
forsinkes pr avgang»
 Sekunders forsinkelse per bil: Forklaringsteksten kan være: «Når de blir forsinket, antall
sekunder»

**Comment by 7er** [comment]
@nilsfearnley Jeg har gjort alt untatt forklaringstekstene her, jeg tror dessverre ikke forklaringstekstene blir ferdig til tirsdag. Er det krise?

**Comment by nilsfearnley** [comment]
Går fint!! Ikke overarbeid deg!
