### ISSUE TITLE
Tusenskille tegn i tiltaksskjema

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#22]
Det hadde gjort det mye mer leselig. 

Dette kan f.eks. gjøres ved å først gjøre om til felter når brukeren klikker på feltet

**Comment by 7er** [comment]
Kunne dette vært gjort på en god måte ved følgende design: Legg til isEditing boolean for hvert Field. La viewet rendre enten verdien i en div (False) eller input box (True). Legg på en onFocus FieldEdit <field> True og onBlur FieldEdit <field> False. Håndter FieldEdit i update ved å sette isEditing boolean for feltet.

**Comment by thomasfl** [comment]
Absolutt. Jeg formatterer beløpet på onBlur her https://bitgate-prototype.herokuapp.com

**Comment by thomasfl** [comment]
Nettbanken til DnB formaterer også beløp på onBlur

**Comment by 7er** [comment]
Kult, da grabber jeg den. Jeg får nok ikke sett på det før til helgen. Det er fullt trøkk med backend koding på telenor.

**Comment by thomasfl** [comment]
Hold ut til helgen. Da kan du slippe frem i frontendlyset igjen.
