### ISSUE TITLE
La bruker grafe vilkårlige forutsetninger når hele tiltaksskjemaet er utfylt

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#23]
Grafen viser hvordan tiltakets nettonåverdi varierer med <valgt forutsetningsnavn>

**Comment by 7er** [comment]
@nilsfearnley Ad tilbakemelding fra Harald Aas:
* Får stadig opp feilmeldingen «Mangler data for å grafe» (å grafe er dessuten kanskje et litt uvanlig verb??)

Dette er ikke en feilmelding. Og den kommer til å være der langt sjeldnere når featuren beskrevet her er implmentert. Men meldingen burde sikkert være bedre, slik at man ikke tror det er en feil.

Når denne featuren er ferdig så kan meldingen f.eks være. "Flere forutsetninger må fylles ut for at vi skal kunne tegne opp grafen" eller noe slikt. Har dere noen ideer @thomasfl @nilsfearnley ?

**Comment by thomasfl** [comment]
Hvis man endrer teksten "Mangler data for å grafe" til "Legg inn flere tall for å vise graf", så ser det ikke ut som en feilmelding. Teksten "Grafen viser hvordan tiltakets nettonåverdi varierer med <forutsetnings navn her>", trenger ikke være vises når grafen ikke vises. Vi kunne også vurdere å legge inn tooltip med ordforklaring på "nettonåverdi".

Muligheten for å endre hvilken variabel som skal vises på y-aksen, bør enten ikke vises eller ikke være tilgjengelig (disablet) når grafen ikke vises.
