### ISSUE TITLE
Opprop av neste holdeplass om bord: Nettonytte per budsjettkrone

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#25]
Denne finnes ikke i regnearket. Og det er vel egentlig meningsløst siden dette tiltaket ikke har en kostnad. Skal vi bare fortelle brukeren at dette elementet i analysen ikke gjelder for dette tiltaket?

Jeg setter denne til Designer-Thomas også kanskje han har noe perspektiv på dette

**Comment by nilsfearnley** [comment]
Ja, det stemmer. Det gir ingen mening med nettonytte per budsjettkrone eller nyttekostnadsbrøk. Eneste formål er å vise nytten, som er stor. 

Men det kan kanskje rote til oppsettet deres, med graf osv som blir overflødig? I så fall kunne det passe med en tekst under tiltaksnavnet: "Dette tiltaket har ingen kostnadsside. Derfor beregnes kun brukernytten." eller noe sånt.

**Comment by 7er** [comment]
Ja nemlig, det roter til oppsettet. Men det er selvfølgelig helt mulig å gjøre dette tiltaket litt custom ved å fjerne hele graf-greiene og fjerne biter av analysen.

Spørsmålet blir da prioritering. Er dette tiltaket prioritert å få på plass til Seminaret eller kan det prioriteres ned?

**Comment by nilsfearnley** [comment]
Lavt prioritert!
