### ISSUE TITLE
Gjenstående tiltak

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#27]
Nils 27/10 kl 15:19: 
Jeg justerte listen i selve kommentaren, nedenfor.
Koll.prioritering ved skilting tror jeg er identisk med koll.prioritering ved lyskryss, så potensielt veldig kjapp å sette opp.
Hilsen Nils

----
Under er de gjenstående tiltakene vi ble enige om med de lavest prioriterte nederst. Kunne du Nils, putte de høyest prioriterte til toppen av listen.

- [x] Kollektivprioritering ved skilting
- [x] Bussrenhold
- [x] Laventrebuss
- [x] Kantsteinstopp

**Comment by thomasfl** [comment]
Oj.

**Comment by 7er** [comment]
Setter strek her
