### ISSUE TITLE
Tilgjengelighetsgruppe

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#29]
Kan vi ha en boks som egentlig bare har et utvalg av de samme tiltakene som er i andre bokser?
I så fall foreslår jeg en NY BOKS som grupperer tilgjengelighetstiltakene (her fra excel-filen, jeg vet at
ikke alle tiltakene er klare):

Tilgjengelighet
 Opphøyet holdeplass
 Pakke: Leskur og sitteplass på holdeplass (Nytt navn: Leskur med sitteplass)
 Sitteplass på holdeplass
 Økt renhold på holdeplass
 Økt fjerning av is og snø på holdeplass
 Elektronisk skilting om bord om neste holdeplass
 Opprop av neste holdeplass om bord
 Pakke: Opprop om neste holdeplass og elektronisk skilting om bord (NB Nytt navn:
Elektronisk skilting og opprop i bussen av neste holdeplass»)
 Informasjon over høyttaler på holdeplass om avvik
 Belysning på holdeplass
 Lavgulvbuss

**Comment by 7er** [comment]
Er denne prioritert for seminaret ditt @nilsfearnley ?

**Comment by nilsfearnley** [comment]
Hvis det er kjapt gjort, så JA. 
Det et seminar om Universell Utforming, så fint å fremheve det.
For å gjøre det enkelt, kan ikonet til boksen være to store u'er, altså: UU

**Comment by thomasfl** [comment]
Allle de andre ikonene er hentet the The Noun Project https://thenounproject.com

Det er veldig mange ikoner der.

**Comment by nilsfearnley** [comment]
Hva med å kombinere noen ikoner for tunghørt, rullestol, synshemmet, mye bagasje?
https://thenounproject.com/ArtZ91/collection/accessibility/?oq=accessibility&cidx=0&i=1033837
https://thenounproject.com/ArtZ91/collection/accessibility/?oq=accessibility&cidx=0&i=1033836
https://thenounproject.com/search/?q=sight impaired&i=197505
