### ISSUE TITLE
Bussrenhold spørsmål

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#31]
Felt B8 er ikke i bruk såvidt jeg kan se.

Investeringsfaktoren ser heller ikke ut til å være i bruk, dvs. at levetiden ikke er i bruk heller.

Antakelig har ikke Bussrenhold noen installasjonskostnad, det virker ihvertfall intuitivt riktig. Jeg antar at de ekstra feltene som ikke er i bruk bare er feil og går videre med implementasjonen av tiltaket

**Comment by nilsfearnley** [comment]
Ja, det stemmer. Det er kostnad per år (egentlig feil å benevne dette som "årlige drifts- og vedlikeholdskostnader" for det er bare "årlig kostnad".
Ingen investeringskostnad. Kun årlige kostnader. Levetiden blir 1 år.
