### ISSUE TITLE
Laventrebuss spørsmål

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#35]
Det er et felt "Andel passasjerer som benytter høye holdeplasser" her. Er det meningsfylt at brukeren skal fylle ut dette? Trenger man høye holdeplasser når man har laventre buss?

**Comment by 7er** [comment]
Jeg har sett mer på kalkulasjonene og tror jeg har skjønt det. Høye holdeplasser er holdeplasser spesielt tilpasset laventre-busser, mens de resterende prosentene er utilpassette holdeplasser. Da ser det igrunnen fornuftig ut.

**Comment by nilsfearnley** [comment]
Ja, det er nok faktisk riktig. Laventre uten høy holdeplass blir ikke fullstendig trinnfritt.
