### ISSUE TITLE
Henvisning til rapporten

### ISSUE THREAD

**Issue by 7er** [7er/elm-nka#50]
@nilsfearnley 

> 1.5 Henvisning til «rapporten»
> Alle steder hvor det står «se rapport for forklaring», bør det stå «Se TØI-rapport 1121 for forklaring» (altså med rapportnummer og lenke).

Det går ikke an å ha en link som placeholder tekst inne i et input felt. Men det hadde gått an å ha en link i selve felt tittelen.

Se Opphøyet Holdeplass tiltaket i verktøyet
Felt tittelen er "Årlig tidsbesparelse ved raskere på- og avstigning, minutter"
Felt placeholder er "Se forklarende tekst i rapport"

Hvis du kan komme med et forslag til tekst for tittel og placeholder hvor linken er i felt tittelen så kan jeg enkelt gjøre det

**Comment by nilsfearnley** [comment]
OK. Hva med:
Felt tittelen er "Årlig tidsbesparelse (se [rapport](https://www.toi.no/getfile.php?mmfileid=6042))"
Felt placeholder er "Tidsbesparelse ved raskere på- og avstigning, minutter"

**Comment by 7er** [comment]
Det høres sweet ut. Da skal jeg få programmert det
